HW_2
alexqrid/2019-2-Atom-Frontend-A-Gridin pull request #2
Opened 2019-11-02 14:26 UTC by alexqrid

# Домашнее задание №

Прошу @martinkomitsky, @chexex или @priver проверить его.

Что было сделано:
Наконец-то сверстал страницу по макету. Но не понял как навесить обработчик на кнопку,если она из другого компонента.

2019-11-05 11:08 UTC, priver requested changes
нужно выкатить на github pages.

напиши комментарий к коду (прям на нужной строчке) где у тебя что не получилось

2019-11-05 12:44 UTC, alexqrid commented
> нужно выкатить на github pages.
> 
> напиши комментарий к коду (прям на нужной строчке) где у тебя что не получилось

Написал комментарий по поводу моего вопроса в файл FormInput.js.
С деплоем  пока всё плохо, Алексей пытается помочь.

2019-11-07 13:14 UTC, priver commented on web-components/src/components/FormInput.js
> +        */
можно сделать метод например `addSubmitListener(fn)` который будет принимать функцию и добавлять ее обработчиком на клик. вызывать этот метод из родительского компонента и передавать этот обработчик

2019-11-11 17:04 UTC, alexqrid commented on web-components/src/components/FormInput.js
> +        */
Не работает так, потому что функция из родительского компонента находится в классе и завязана она на атрибутах класса соответственно.

2019-11-11 17:18 UTC, priver commented on web-components/src/components/FormInput.js
> +        */
я не могу отвечать на пространные вопросы про "завязано", у нас тут не швейная фабрика. сделай как получится и напиши что именно у тебя не работает

2019-11-11 17:52 UTC, alexqrid commented on web-components/src/components/FormInput.js
> +        */
Всё сделано давно и работает по условию домашки,а про кнопочку хотелось добавить такой логичный функционал, ибо в домашке нет условия такого.

2019-11-14 10:21 UTC, priver approved these changes
6 баллов

2019-11-14 10:21 UTC, merged